Добавит конфиг для yaspeller и пример общего словаря
htmlacademy/configs pull request #1
Opened 2020-05-18 15:56 UTC by sashasushko

Предложение моё такое, что в этот конфиг попадают общие слова, которые встречаются или могут встретиться на всех курсах (типа "колбэк"), а в локальные словари - слова конкретного курса (например "редьюсер" в курсе по Реакту).

Текущая реализация основную функцию выполняет. Можно установить в проект, подключить и всё будет проверяться. Из критичных проблем: пока не разобрался, как научить спеллер самостоятельно понимать склонения и мн./ед.число, чтобы не писать `колбэк(а)?`.

2020-05-19 00:54 UTC, AntonovIgor approved these changes
:+1: У меня предложение по наполнению начального состояния словаря. Можно взять термины из словаря по фронтенду https://github.com/web-standards-ru/dictionary. @pepelsbey с ребятами собрал много терминов. Многие из них наверняка будут встречаться в статьях учебника. Я к нему постоянно обращаюсь.

2020-05-19 11:50 UTC, kicumkicum commented on readme.md
> +Ищет опечатки в материалах. Для настройки необходимо в репозитории курса указать путь к файлу конфигурации.
Если реп публичный и позиционируется как _общие конфиги_, то слово _курс_ писать не нужно.

```suggestion
Ищет опечатки в материалах. Для настройки необходимо в своем репозитории указать путь к файлу конфигурации.
```

2020-05-19 11:52 UTC, kicumkicum commented on readme.md
> +При необходимости можно завести [словарь](https://github.com/hcodes/yaspeller#--dictionary-file) конкретного курса и расширить общий:
Вот это не понятно. Что это значит? Имеется ввиду тут завести или в репе интенсива?

2020-05-19 11:53 UTC, kicumkicum requested changes
👍

2020-05-19 12:43 UTC, sashasushko commented on readme.md
> +При необходимости можно завести [словарь](https://github.com/hcodes/yaspeller#--dictionary-file) конкретного курса и расширить общий:
В репе конкретного курса

2020-05-19 13:01 UTC, sashasushko commented on readme.md
> +Ищет опечатки в материалах. Для настройки необходимо в репозитории курса указать путь к файлу конфигурации.
Да, тогда нужно скорректировать `readme.md` в целом. Давай это отдельным пулл реквестом зарешаем

2020-05-19 13:26 UTC, kicumkicum requested changes

2020-05-19 13:26 UTC, kicumkicum commented on readme.md
> +При необходимости можно завести [словарь](https://github.com/hcodes/yaspeller#--dictionary-file) конкретного курса и расширить общий:
```suggestion
При необходимости можно расширить базовый [словарь](https://github.com/hcodes/yaspeller#--dictionary-file) в своём репе:
```

2020-05-19 13:26 UTC, kicumkicum commented on readme.md
> +_`js-3-dictionary.json` — словарь конкретного курса в той же директории, где и `package.json`._
```suggestion
_`js-3-dictionary.json` — дополняющий словарь должен находиться в той же директории, где и `package.json`._
```

2020-05-19 13:26 UTC, kicumkicum commented on readme.md
> +Ищет опечатки в материалах. Для настройки необходимо в репозитории курса указать путь к файлу конфигурации.
Прими три саджеста и дело закрыто :)

2020-05-20 07:35 UTC, sashasushko commented on readme.md
> +Ищет опечатки в материалах. Для настройки необходимо в репозитории курса указать путь к файлу конфигурации.
Как MVP норм, но "маловато будет". Даже если сравнить с ё-моё. Так что за саджесты спасибо, но пулл реквест отдельный всё равно нужен.

2020-05-20 07:36 UTC, sashasushko commented on readme.md
> +_`js-3-dictionary.json` — словарь конкретного курса в той же директории, где и `package.json`._
Кстати, это не обязательно поэтому "должен находиться" некорректно

2020-05-22 12:13 UTC, nikolai-shabalin approved these changes

2020-05-22 14:12 UTC, kicumkicum approved these changes

2020-06-19 10:58 UTC, merged