Добавляет editorConfig
htmlacademy/configs pull request #12
Opened 2021-03-31 14:38 UTC by nikolai-shabalin

2021-04-02 17:27 UTC, sashasushko requested changes
Давай ещё в ридми отразим, что это не просто файл, а файл - который нужно взять и положить к себе в другие репы

2021-04-07 16:18 UTC, a-seredkin approved these changes

2021-04-15 11:33 UTC, nikolai-shabalin commented
@sashasushko можешь ещё раз глянуть? Если норм, то замерж, плз

2021-04-16 10:57 UTC, sashasushko approved these changes

2021-04-16 10:58 UTC, merged