Добавит линтер для Markdown
htmlacademy/configs pull request #14
Opened 2021-04-05 16:16 UTC by levallevchenko

2021-04-06 11:06 UTC, sashasushko requested changes

2021-04-06 11:06 UTC, sashasushko commented on readme.md
> +markdownlint --config ./.markdownlint.yml <markdown-файл или директория с файлами>
Этот репозиторий распространяется как npm-пакет и для конфига Markdown нужно сделать всё, как для конфига Yaspeller, чтобы не копировать руками.

2021-04-06 11:06 UTC, sashasushko commented on .markdownlint.yml
> +dafault: true
```suggestion
default: true
```
?

2021-04-06 11:06 UTC, sashasushko commented on package.json
> +  "devDependencies": {
В самом этом репозитории markdownlint-cli не нужен, как зависимость

2021-04-06 11:06 UTC, sashasushko commented on .markdownlint.yml
> +dafault: true
Сами правила нужно в этом пулл реквесте расписать, чтобы если кто не согласен, сразу отписался об этом.

2021-04-06 15:15 UTC, levallevchenko commented
### Действующие правила
MD03 — единообразный стиль заголовков
MD05 — единообразные отступы для элементов списка на одном уровне

2021-04-07 16:20 UTC, sashasushko requested changes
Отличная работа. Оставил замечания по пунктам.

Я бы ещё добавил правило https://github.com/byzyk/markdownlint-rule-emphasis-style - это не совсем то, что было нужно изначально, но тоже подойдёт

2021-04-07 16:20 UTC, sashasushko commented on .markdownlint.yml
> +MD002: false
> MD002 has been deprecated and is disabled by default

Нужно ли нам перечислять дефолтные, если в начале файла есть `default: true`?

2021-04-07 16:20 UTC, sashasushko commented on .markdownlint.yml
> +MD004:
Почему-то пропущено MD003, я бы установил его в `atx`, чтобы только заголовки с решётками были

2021-04-07 16:20 UTC, sashasushko commented on .markdownlint.yml
> +  line_length: 1000
> Возможно, можно вообще отключить

Предлагаю вообще отключить

2021-04-07 16:20 UTC, sashasushko commented on .markdownlint.yml
> +MD024: false
Я бы оставил, пока не столкнёмся с проблемой

2021-04-07 16:20 UTC, sashasushko commented on .markdownlint.yml
> +MD026: false
Я бы тоже оставил правило, только разрешил `?`, `...` и `!`

2021-04-07 16:20 UTC, sashasushko commented on .markdownlint.yml
> +MD036: false
Я бы добавил MD035 как `---`

2021-04-07 16:21 UTC, sashasushko requested changes

2021-04-07 16:21 UTC, sashasushko commented on readme.md
> +        "markdownlint": "markdownlint --config ./.markdownlint.yml ."
Ещё, пути то будут как у yaspeller
```suggestion
        "markdownlint": "markdownlint --config ./node_modules/@htmlacademy/configs/.markdownlint.yml ."
```

2021-04-07 16:21 UTC, sashasushko commented on readme.md
> +        "markdownlint": "markdownlint --config ./.markdownlint.yml ."
И файл можно не называть с точки

2021-04-07 16:25 UTC, levallevchenko commented on .markdownlint.yml
> +MD002: false
Нашла, подобное применение в чужом конфиге. Вообще раз написано, что оно отключено, наверное, не нужно отдельно прописывать, проверю.

2021-04-14 09:59 UTC, levallevchenko commented on .markdownlint.yml
> +MD002: false
Удалила отдельное правило

2021-04-14 10:01 UTC, levallevchenko commented on .markdownlint.yml
> +  line_length: 1000
Отключила

2021-04-14 10:02 UTC, levallevchenko commented on .markdownlint.yml
> +MD024: false
Оставила

2021-04-14 10:10 UTC, levallevchenko commented on .markdownlint.yml
> +MD004:
Добавила

2021-04-14 10:24 UTC, levallevchenko commented on .markdownlint.yml
> +MD026: false
Добавила запрещающие символы, кажется можно именно так, не нашла, как добавить разрешённые символы

2021-04-14 10:25 UTC, levallevchenko commented on .markdownlint.yml
> +MD036: false
Добавила

2021-04-14 12:50 UTC, sashasushko requested changes

2021-04-14 12:50 UTC, sashasushko commented on readme.md
> +        "markdownlint:fix": "markdownlint --fix ./.markdownlint.yml ."
А ты проверяла, не нужен ли в этом случае и флаг `--config`?

2021-04-14 12:50 UTC, sashasushko commented on readme.md
> +        "markdownlint:fix": "markdownlint --fix ./.markdownlint.yml ."
И здесь путь тоже должен быть от `node_modules`

2021-04-15 11:16 UTC, levallevchenko commented on readme.md
> +        "markdownlint:fix": "markdownlint --fix ./.markdownlint.yml ."
Да, забыла, что было два скрипта в Readme. Всё поправила 0444d88. Проверила `--сonfig` нужен, чтобы наши правила применялись, а не дефолтные.

2021-04-15 11:18 UTC, levallevchenko commented on readme.md
> +        "markdownlint:fix": "markdownlint --fix ./.markdownlint.yml ."
Добавила ещё игнор всех node-modules

2021-04-15 11:26 UTC, sashasushko requested changes

2021-04-15 11:26 UTC, sashasushko commented on readme.md
> +        "markdownlint": "markdownlint --config ./node_modules/@htmlacademy/configs/markdownlint.yml --ignore node_modules ."
```suggestion
        "markdownlint": "markdownlint --config ./node_modules/@htmlacademy/configs/.markdownlint.yml ."
```

2021-04-15 11:26 UTC, sashasushko commented on readme.md
> +        "markdownlint": "markdownlint --config ./node_modules/@htmlacademy/configs/markdownlint.yml --ignore node_modules ."
Не нужно этого. Каждый, кто утащит себе, сам укажет директорию, которую нужно линтить, и сам исключит те, которые не нужно.

2021-04-15 11:26 UTC, sashasushko commented on readme.md
> +        "markdownlint:fix": "markdownlint --fix --config ./node_modules/@htmlacademy/configs/markdownlint.yml --ignore node_modules ."
```suggestion
        "markdownlint:fix": "markdownlint --fix --config ./node_modules/@htmlacademy/configs/.markdownlint.yml ."
```

2021-04-15 11:26 UTC, sashasushko approved these changes

2021-04-15 11:41 UTC, nikolai-shabalin approved these changes

2021-04-15 18:28 UTC, a-seredkin approved these changes

2021-04-16 07:32 UTC, sashasushko commented
@levallevchenko можно мёржить. Только Merge and squash

2021-04-16 10:59 UTC, sashasushko commented
И ишью https://github.com/htmlacademy/configs/issues/5 закрыть надо будет после

2021-04-16 16:25 UTC, merged