Добавит в словарь исключения из раздела Помощь
htmlacademy/configs pull request #3
Opened 2020-11-10 10:42 UTC by sashasushko

Ориентировался на https://github.com/web-standards-ru/dictionary

2020-11-10 11:48 UTC, pepelsbey requested changes

2020-11-10 11:48 UTC, pepelsbey commented on yaspeller.json
> +        "Гитхаб(е)?",
```suggestion
        "Гитхаб(е|)?",
```
Чтобы прошло слово Гитхаб, нужно ещё добавить пайп в конец. Здесь и в других местах, где слово без скобочек тоже правильное.

2020-11-10 13:55 UTC, sashasushko commented on yaspeller.json
> +        "Гитхаб(е)?",
@pepelsbey а ты уверен, что это не одно и то же: `(е|)` и `(е)?`? Проверил локально, с `Гитхаб(е)?`-правилом слово `Гитхаб` в тексте ошибки не вызывает

2020-11-10 14:11 UTC, pepelsbey commented on yaspeller.json
> +        "Гитхаб(е)?",
У меня не работает без финального пайпа `|)`

<img width="464" alt="image" src="https://user-images.githubusercontent.com/105274/98684862-bafaa180-2377-11eb-80e1-907a4f562420.png">

2020-11-10 16:59 UTC, sashasushko commented on yaspeller.json
> +        "Гитхаб(е)?",
С "воркером" проблема, что я забыл в конце `?`

2020-11-10 16:59 UTC, sashasushko commented on yaspeller.json
> +        "Гитхаб(е)?",
Проверю дополнительно

2020-11-10 17:01 UTC, sashasushko commented on yaspeller.json
> +        "Гитхаб(е)?",
`?` после блока `()` помечает его опциональным

2020-11-10 18:58 UTC, pepelsbey commented on yaspeller.json
> +        "Гитхаб(е)?",
Окей, я понял. Здесь просто используется другой синтаксис. Либо вопрос, либо пустой пайп — мне так понятнее и привычнее, но разницы нет.

2020-11-10 18:59 UTC, pepelsbey approved these changes

2020-11-13 09:26 UTC, AntonovIgor approved these changes
👍

2020-11-16 11:25 UTC, nikolai-shabalin approved these changes

2020-12-17 15:19 UTC, merged