Добавит в словарь новые слова
htmlacademy/configs pull request #8
Opened 2021-02-09 18:00 UTC by levallevchenko

2021-02-10 14:55 UTC, sashasushko commented on yaspeller.json
> +        "отрисовк(а|у|и|ой)",
@nikolai-shabalin вам пригодится?

2021-02-10 15:49 UTC, nikolai-shabalin commented on yaspeller.json
> +        "отрисовк(а|у|и|ой)",
Ты про отрисовку или все добавленные? Хотя ответ - да, пригодится.
В целом, я уже к нам забираю.

2021-02-10 15:50 UTC, nikolai-shabalin approved these changes

2021-02-10 19:15 UTC, sashasushko commented on yaspeller.json
> +        "отрисовк(а|у|и|ой)",
Про отрисовку. Про все добавленные - это я твоё ревью запросил.

2021-02-11 11:02 UTC, levallevchenko commented on yaspeller.json
> +        "контринтуитивн(ая|ый|ые|ого)",
Дубль с 23 строкой

2021-02-11 11:24 UTC, levallevchenko commented on yaspeller.json
> +        "отрис(овать|овывать|овывает|ует|уют|уюем)",
Не хватает   
"отрис(ованный | ованная | ованные | ован | ована | ованы | овывающий | уйте | овки | овывалась | овывался | овывались | овался | овалась | овались | овалось)"

2021-02-11 11:24 UTC, levallevchenko commented on yaspeller.json
> +        "переиспольз(уемый|уемые|уемая|ованный|ованная|ованные)",
переиспользовать

2021-02-11 12:59 UTC, levallevchenko commented on yaspeller.json
> +        "переиспольз(уемый|уемые|уемая|ованный|ованная|ованные)",
Добавить «форк», «мёржить», «GitHub»,«ESlint», "коллаборатор(а|у|ы|ов)?", "коммит(ы|а|у|ов|ам|ить|ят)?", "закоммит(ить|ят)?", "Правдорубов", "Travis", "шаблонизатор", "шаблонизация", "техзадание", "валидировать",
  "провалидировать", "валидация",

2021-02-11 15:27 UTC, sashasushko approved these changes

2021-02-11 15:32 UTC, sashasushko requested changes

2021-02-11 15:32 UTC, sashasushko commented on yaspeller.json
> +        "закомментир(овать|уем|ует|ованный|ованная|)",
```suggestion
        "закомментир(овать|уем|ует|ованный|ованная)?",
```

2021-02-12 11:38 UTC, levallevchenko commented on yaspeller.json
> +        "закомментир(овать|уем|ует|ованный|ованная|)",
А здесь нужен `?`.  «закомментир» же нет слова. Удалю просто `|`?

2021-02-12 12:24 UTC, sashasushko commented on yaspeller.json
> +        "закомментир(овать|уем|ует|ованный|ованная|)",
Да, тогда просто удали

2021-02-15 08:13 UTC, merged